# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\"\x07\n\x05\x45mpty\";\n\x11\x43reateRoomRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\"7\n\x0fJoinRoomRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\"T\n\x08RoomInfo\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\x12\x14\n\x0cplayer_count\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\"*\n\tLobbyList\x12\x1d\n\x05rooms\x18\x01 \x03(\x0b\x32\x0e.game.RoomInfo\"6\n\x10SubscribeRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\"U\n\x0bMoveRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\"\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x12.game.PlayerAction\"6\n\x0cMoveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x89\x02\n\tGameState\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0cplayer1_name\x18\x03 \x01(\t\x12\x14\n\x0cplayer2_name\x18\x04 \x01(\t\x12\x15\n\rplayer1_lives\x18\x05 \x01(\x05\x12\x15\n\rplayer2_lives\x18\x06 \x01(\x05\x12\x1e\n\x16\x63urrent_turn_player_id\x18\x07 \x01(\t\x12\x17\n\x0f\x62ullets_in_clip\x18\x08 \x01(\x05\x12\x1c\n\x14live_bullets_in_clip\x18\t \x01(\x05\x12\x17\n\x0flast_action_log\x18\n \x01(\t\x12\x11\n\twinner_id\x18\x0b \x01(\t*A\n\x0cPlayerAction\x12\x12\n\x0eSHOOT_OPPONENT\x10\x00\x12\x0e\n\nSHOOT_SELF\x10\x01\x12\r\n\tQUIT_GAME\x10\x02\x32\x9a\x02\n\nGameServer\x12*\n\nGetLobbies\x12\x0b.game.Empty\x1a\x0f.game.LobbyList\x12\x35\n\nCreateRoom\x12\x17.game.CreateRoomRequest\x1a\x0e.game.RoomInfo\x12\x31\n\x08JoinRoom\x12\x15.game.JoinRoomRequest\x1a\x0e.game.RoomInfo\x12\x31\n\x08MakeMove\x12\x11.game.MoveRequest\x1a\x12.game.MoveResponse\x12\x43\n\x16SubscribeToGameUpdates\x12\x16.game.SubscribeRequest\x1a\x0f.game.GameState0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERACTION']._serialized_start=744
  _globals['_PLAYERACTION']._serialized_end=809
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_CREATEROOMREQUEST']._serialized_start=29
  _globals['_CREATEROOMREQUEST']._serialized_end=88
  _globals['_JOINROOMREQUEST']._serialized_start=90
  _globals['_JOINROOMREQUEST']._serialized_end=145
  _globals['_ROOMINFO']._serialized_start=147
  _globals['_ROOMINFO']._serialized_end=231
  _globals['_LOBBYLIST']._serialized_start=233
  _globals['_LOBBYLIST']._serialized_end=275
  _globals['_SUBSCRIBEREQUEST']._serialized_start=277
  _globals['_SUBSCRIBEREQUEST']._serialized_end=331
  _globals['_MOVEREQUEST']._serialized_start=333
  _globals['_MOVEREQUEST']._serialized_end=418
  _globals['_MOVERESPONSE']._serialized_start=420
  _globals['_MOVERESPONSE']._serialized_end=474
  _globals['_GAMESTATE']._serialized_start=477
  _globals['_GAMESTATE']._serialized_end=742
  _globals['_GAMESERVER']._serialized_start=812
  _globals['_GAMESERVER']._serialized_end=1094
# @@protoc_insertion_point(module_scope)
